/* Automatically generated by './build/bin/build-entry.js' */

import SungrowFooter from '../packages/sungrow-footer/index.js'

const components = [
  SungrowFooter
]

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.0.1',
  install,
  SungrowFooter
}
