/* Automatically generated by './build/bin/build-entry.js' */

import EncounterFilter from '../packages/encounterFilter/index.js'
import Footer from '../packages/footer/index.js'

const components = [
  EncounterFilter,
  Footer
]

const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.0.4',
  install,
  EncounterFilter,
  Footer
}
